### ISSUE TITLE
Hash (filename) is always the same

### ISSUE THREAD

**Issue by specimen151** [ServiceStackApps/Imgur#1]
When debugging, I always get the same filename/hash from GetMd5Hash(Stream stream), even after restart and with many different images. I've verified that the stream actually contains different data.

This seems to solve the problem:

```
byte[] imgBytes = stream.ToArray();
var hash = MD5.Create().ComputeHash(imgBytes);
```

**Comment by mythz** [comment]
What OS/platform is it returning the same hash on?

**Comment by specimen151** [comment]
Windows 8.1 net 4.5.

**Comment by mythz** [comment]
ok thx should be resolved with this commit: https://github.com/ServiceStackApps/Imgur/commit/1de9e6e24b243647839405b76fba803dcb41097b

**Comment by specimen151** [comment]
I'm sorry to say it still doesn't work. Maybe it's a .NET bug. Only .ToArray() seems to read the stream. ReadFully() or GetBytes() and results in byte[0].

(another SS related bug is that DTO ToAbsoluteUri gives a relative URI, sorry to mention it here. It is the HostConfig's WebHostUrl which is never set, unless I'm mistaken)

**Comment by mythz** [comment]
Right it needs `Config.WebHostUrl` to be explicitly set if used outside the context for a HTTP Request otherwise it has no idea what base url to use, e.g:

``` csharp
SetConfig(new HostConfig {
    WebHostUrl = baseUrl,
})
```

**Comment by specimen151** [comment]
It is inside a service (the Post service in Imgur). Want to have it return the full URL for the Get Resize operation for the image just posted. Doing a 

```
new Resize{Id=hash}.ToAbsoluteUrl() 
```

returns a relative URL. 

BTW still need ToArray() to get the hash to work, or else byte[] has length 0.

**Comment by mythz** [comment]
Are you running this on ASP.NET/Windows or something else?

**Comment by specimen151** [comment]
Windows 8.1 ASP.net IIS express (debugging from visual studio). 2013 Community edition. 
Regular AppHost from AppHostBase. 

```
<?xml version="1.0" encoding="utf-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=169433
 -->
<configuration>
  <configSections>
    <sectionGroup name="system.web.webPages.razor"     type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
  <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false" />
  <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false" />
    </sectionGroup>
  </configSections>

  <system.web>
    <compilation targetFramework="4.5" debug="true"><buildProviders>
        <add extension=".cshtml" type="ServiceStack.Razor.CSharpRazorBuildProvider, ServiceStack.Razor" />
      </buildProviders></compilation>
    <httpRuntime targetFramework="4.5" />
     <httpHandlers>
      <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" />
    </httpHandlers>
   </system.web>
  <system.webServer>
     <validation validateIntegratedModeConfiguration="false" />
    <urlCompression doStaticCompression="true" doDynamicCompression="false" />
    <handlers>
       <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
    </handlers>
   </system.webServer>
  </configuration>
```

**Comment by mythz** [comment]
Should now be resolved with latest commit. 

`AbsoluteUrl()` required specifying the BaseUrl with:

``` csharp
SetConfig(new HostConfig {
    WebHostUrl = baseUrl
});
```

But I've added an update so `ToAbsoluteUri()` works in ASP.NET without specifying the BaseUrl (or passing in IRequest), this required updating to use the latest v4.0.37 packages that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by specimen151** [comment]
Thanks, I can confirm that `ToAbsoluteUri()` on the DTO object now works correctly in ASP.NET without any extra work.

I can also confim that the latest commit "reset stream" makes the hash calculation work correctly (but I guess you already knew that).
